
### PRDODUCT ###
POST http://localhost:3000/product/ 
    Content-Type: application/json

    {
        "name": "Whiskas 3.9KG",
        "price":208,
        "desc": "Fooder from Whiskas.",
        "image":"https://images-eu.ssl-images-amazon.com/images/I/61STdNV9bfL._AC_UL600_SR600,600_.jpg",
        "createdAt":"2023-09-21",
        "tags":["cat","fooder","food"]
    
    }

###

PUT http://localhost:3000/product/:id
    Content-Type: application/json

    {
        "_id":"65071294418342c9c5d7f7dc",
        "price":1199,
        "name":"Cat barrel"
    }

###

GET http://localhost:3000/product/ 
    Content-Type: application/json

### ORDER ###

GET http://localhost:3000/order/ 
    Content-Type: application/json

    
###

POST http://localhost:3000/order/ 
    Content-Type: application/json

    {
        "cFirstname": "Bob",
        "cLastname":"Dylan",
        "cPhone": 132123321,
        "cAdress":[{
            "street":"frontendstreet 22",
            "city": "Fullstackville",
            "zipcode":12345
        }],
        "products":[{
            "name":"Super Litterbox 1000",
            "price": 600
        },
        {
            "name":"Super Litterbox 23",
            "price":200
        }],
        "totalCost":800,
        "deliveryOption": "Postnord",
        "freeShipping": "true",
        "shipped": false,
        "paymentOption": "CARD"
    
    }

###

PUT http://localhost:3000/order/:_id
    Content-Type: application/json

    {
        "_id":"65070af7184e3b53308db034",
        "shipped":"false"
    }
